/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mlsystem.form;

import com.mlsystem.dao.ReadXMLFileDAO;
import com.mlsystem.dao.ReadXMLFileDAOImpl;
import com.mlsystem.dao.UserInterfaceConfigurationDAO;
import com.mlsystem.entity.Company;
import com.mlsystem.entity.Person;
import com.mlsystem.service.UserManager;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.apache.commons.dbcp.BasicDataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Marcin
 */
@Component
public class Login_form extends javax.swing.JFrame {

    @Autowired
    UserManager userManager;
    
    @Autowired
    TechnologForm technologForm;
    
    @Autowired
    BasicDataSource dataSource;
    
    @Autowired
    ReadXMLFileDAO   rdao ;
    
    //@Autowired
    UserInterfaceConfigurationDAO uicDAO;
    
    /**
     * Creates new form Login_form
     */
    public Login_form() {

        initComponents();       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExecuteButton1 = new javax.swing.JButton();
        jLoginField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jExecuteButton1.setText("jButton1");
        jExecuteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExecuteButton1ActionPerformed(evt);
            }
        });

        jLoginField1.setText("postgres");
        jLoginField1.setToolTipText("login");
        jLoginField1.setMaximumSize(new java.awt.Dimension(48, 20));
        jLoginField1.setMinimumSize(new java.awt.Dimension(48, 20));
        jLoginField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLoginField1KeyReleased(evt);
            }
        });

        jLabel1.setText("User");

        jLabel2.setText("Haslo");

        jPasswordField1.setText("postgres");
        jPasswordField1.setToolTipText("Hasło?");
        jPasswordField1.setMaximumSize(new java.awt.Dimension(54, 20));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(54, 20));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jExecuteButton1)
                    .addComponent(jLoginField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jExecuteButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void testowa(){
        Person user = new Person();
    	user.setUsername("johndoe");
    	user.setName("John Doe");
    	
        
    	Company company = new Company();
        company.setCompanyName("lol1");
        
    	userManager.insertUser(user);
    	
    	System.out.println("User inserted!");
    	
    	user = userManager.getUser("johndoe");
    	
    	System.out.println("\nUser fetched by username!"
    		+ "\nId: " + user.getId()
    		+ "\nUsername: " + user.getUsername()
    		+ "\nName: " + user.getName());
    	
    	user = userManager.getUserById(user.getId());
    	
    	System.out.println("\nUser fetched by ID!"
    		+ "\nId: " + user.getId()
    		+ "\nUsername: " + user.getUsername()
    		+ "\nName: " + user.getName());
    	
    	List<Person> users = userManager.getUsers();
    	
    	System.out.println("\nUser list fetched!"
        	+ "\nUser count: " + users.size());
        
}
    private void jExecuteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExecuteButton1ActionPerformed
        //Main.setCTX(new ClassPathXmlApplicationContext("spring.xml"));
        //this.dataSource = (BasicDataSource) Main.getCTX().getBean("dataSource");
        setPasswordAndLogin();
        //testowa();
        this.setVisible(false);
        //technologForm.setParentForm(this);
        technologForm.setVisible(true);
    }//GEN-LAST:event_jExecuteButton1ActionPerformed

    private void jLoginField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLoginField1KeyReleased
        //setPasswordAndLogin();
    }//GEN-LAST:event_jLoginField1KeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        //setPasswordAndLogin();
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            //System.out.println("dupda \n\n\n\n\n\n" + rdao);
            rdao.setFileName("configIP.xml");
            uicDAO = rdao.readFileConfiguration(rdao.getDoc().getElementsByTagName("*"));
            //System.out.println("\n\n\n\n\n\n\n kuku: " +uicDAO.getUserName());
            jLoginField1.setText(uicDAO.getUserName());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login_form.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception e){
            Logger.getLogger(Login_form.class.getName()).log(Level.WARNING, null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void setPasswordAndLogin(){
        dataSource.setPassword(jLoginField1.getText());
        dataSource.setUsername(String.valueOf(jPasswordField1.getPassword()));
        System.out.println("pass \n" +
        dataSource.getPassword() + "user \n" + 
                dataSource.getUsername());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExecuteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jLoginField1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
